apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: 851725364551.dkr.ecr.us-west-1.amazonaws.com/github-actions-image:latest  # Update with your ECR repository URL and image name
          ports:
            - containerPort: 8080  # Assuming your application listens on port 8080
